---
####################################
### Installation
####################################
# Common tasks for all Mesos nodes
- name: Add key for Mesosphere repository
  apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0xE56151BF state=present
  sudo: yes
  when: install

- name: Determine Linux distribution distributor
  shell: lsb_release -is | tr '[:upper:]' '[:lower:]'
  register: release_distributor
  when: install

- name: Determine Linux distribution codename
  command: lsb_release -cs
  register: release_codename
  when: install

- name: Add Mesosphere repository to sources list
  copy:
    content: "deb http://repos.mesosphere.io/{{release_distributor.stdout}} {{release_codename.stdout}} main"
    dest: /etc/apt/sources.list.d/mesosphere.list
    mode: 0644
  sudo: yes
  when: install

# Tasks for Master, Slave, and ZooKeeper nodes
- name: Install mesos package
  apt: pkg={{item}} state=present update_cache=yes
  with_items:
    - mesos
  sudo: yes
  when: install

- name: make sure "{{ mesos_install_prefix }}"/etc/mesos dir exists
  file:  path={{ mesos_install_prefix }}/etc/mesos state=directory
  when: install

- name: Disable the Mesos Slave service
  copy:
    content: "manual"
    dest: /etc/init/mesos-slave.override
    mode: 0644
  sudo: yes
  notify:
      - Stop mesos-slave
  when: install

- name: Disable the Mesos Master service
  copy:
    content: "manual"
    dest: /etc/init/mesos-master.override
    mode: 0644
  sudo: yes
  notify:
    - Stop mesos-master
  when: install

####################################
### Installation
####################################

- name: configure masters file
  template: src=masters.j2 dest={{ mesos_install_prefix }}/etc/mesos/masters
  when: configure

####################################
### Master settings
####################################

- name: configure cluster slaves
  template: src=slaves.j2 dest={{ mesos_install_prefix }}/etc/mesos/slaves
  when: configure and mesos_install_mode == "master"
  notify:
   - Restart mesos-master

- name: configure master settings
  template: src=mesos-master.j2 dest=/etc/default/mesos-master
  when: configure and mesos_install_mode == "master"
  notify:
    - Restart mesos-master

- name: Enable the Mesos Master service
  copy:
    content: ""
    dest: /etc/init/mesos-master.override
    mode: 0644
  sudo: yes
  when: start and mesos_install_mode == "master"
  notify:
    - Start mesos-master

- name: Stop and Disable the Mesos Master service
  copy:
    content: "manual"
    dest: /etc/init/mesos-master.override
    mode: 0644
  sudo: yes
  when: stop and mesos_install_mode == "master"
  notify:
    - Stop mesos-master
####################################
### Slave settings
####################################

- name: configure slave settings
  template: src=mesos-slave.j2 dest=/etc/default/mesos-slave
  when: configure and mesos_install_mode == "master"
  notify:
    - Restart mesos-slave

- name: Enable the Mesos Slave service
  copy:
    content: ""
    dest: /etc/init/mesos-slave.override
    mode: 0644
  sudo: yes
  when: start and mesos_install_mode == "slave"
  notify:
      - Start mesos-slave

- name: Stop and Disable the Mesos Slave service
  copy:
    content: "manual"
    dest: /etc/init/mesos-master.override
    mode: 0644
  sudo: yes
  when: stop and mesos_install_mode == "slave"
  notify:
    - Stop mesos-slave

