---
- name: add Mesosphere apt key
  #apt_key: id=E56151BF url=http://keyserver.ubuntu.com/ state=present
  command: apt-key adv --keyserver keyserver.ubuntu.com --recv E56151BF
  tags:
    - install

- name: add Mesosphere apt repository
  apt_repository: repo='deb [arch=amd64] http://repos.mesosphere.io/ubuntu trusty main' state=present update_cache=yes
  tags:
    - install

- name: install Mesos package
  apt: name={{ item }} state=present
  with_items:
    - mesos
    #- marathon
  tags:
    - install

# TODO: add a task for master service 'chckconfig on start' and etc. slave should be deactivated (it must be setted according to some variable in 'hosts' file)
# TODO: add a task for slave service 'chckconfig on start' and etc. master should be deactivated (it must be setted according to some variable in 'hosts' file)

- name: make sure "{{ mesos_install_prefix }}"/etc/mesos dir exists
  file:  path={{ mesos_install_prefix }}/etc/mesos state=directory

# TODO: replace install_mode with node_mode
- name: configure cluster masters
  template: src=masters.j2 dest={{ mesos_install_prefix }}/etc/mesos/masters
  # TODO: install_mode == "slave" ???
  tags:
    - configure

- name: configure cluster slaves
  template: src=slaves.j2 dest={{ mesos_install_prefix }}/etc/mesos/slaves
  when: install_mode == "master"
  tags:
    - configure

- name: setup deploy environment for slave
  template: src=mesos-slave-env.sh.j2 dest={{ mesos_install_prefix }}/etc/mesos/mesos-slave-env.sh
  when: install_mode == "slave"
  tags:
    - configure

- name: setup deploy environment
  copy: src={{ item }} dest={{ mesos_install_prefix }}/etc/mesos/{{ item }}
  with_items:
    - mesos-master-env.sh
    - mesos-deploy-env.sh
  tags:
    - configure

# TODO: replace configure with start (tags)
- name: start Mesos cluster
  command: "{{ mesos_install_prefix }}/sbin/mesos-start-cluster.sh"
  when: install_mode == "master"
  ignore_errors: true
  tags:
    - configure

# TODO: add a task dedicated to turning whole cluster off (tags - stop)
