---
- name: configure cluster masters
  template: src=masters.j2 dest={{ mesos_install_prefix }}/etc/mesos/masters
  tags:
    - configure

- name: configure cluster slaves
  template: src=slaves.j2 dest={{ mesos_install_prefix }}/etc/mesos/slaves
  tags:
    - configure

- name: setup deploy environment
  copy: src={{ item }} dest={{ mesos_install_prefix }}/etc/mesos/{{ item }}
  with_items:
    - mesos-master-env.sh
    - mesos-deploy-env.sh
  tags:
    - configure

- name: start Mesos cluster
  command: "{{ mesos_install_prefix }}/sbin/mesos-start-cluster.sh"
  become: yes
  become_user: "{{ clusteruser }}"
  ignore_errors: true
  tags:
    - start

# it can be run with the command 'ansible-playbook site.yml --tags "stop"'
#- name: stop Mesos cluster
#  command: "{{ mesos_install_prefix }}/sbin/mesos-stop-cluster.sh"
#  #become: yes
#  #become_user: "{{ clusteruser }}"
#  ignore_errors: true
#  tags:
#    - stop