---
- name: add Mesosphere apt key
  #apt_key: id=E56151BF url=http://keyserver.ubuntu.com/ state=present
  command: apt-key adv --keyserver keyserver.ubuntu.com --recv E56151BF
  tags:
    - install

- name: add Mesosphere apt repository
  apt_repository: repo='deb [arch=amd64] http://repos.mesosphere.io/ubuntu trusty main' state=present update_cache=yes
  tags:
    - install

- name: install Mesos package
  apt: name={{ item }} state=present
  with_items:
    - mesos
    #- marathon
  tags:
    - install

- name: make sure "{{ mesos_install_prefix }}"/etc/mesos dir exists
  file:  path={{ mesos_install_prefix }}/etc/mesos state=directory
  tags:
    - install