---
- name: apply common configuration to all nodes
  hosts: all
  sudo: yes
  roles:
    - common
  any_errors_fatal: yes

- name: apply java 8 and mongodb to all nodes
  hosts: all
  remote_user: vagrant
  sudo: yes
  roles:
       - { role: smola.java }
       - { role: greendayonfire.mongodb }

- name: clone and build project on localhost
  hosts: localhost
  remote_user: vagrant
  sudo: yes
  tags:
   -  build
  tasks:
    - git: repo=git@github.com:itmo-escience/SNCrawler.git
           dest=/SNCrawler
           accept_hostkey=True
           key_file="/home/vagrant/project/sshkey/id_rsa"
           clone=yes update=yes

    - shell: mvn clean install
      args:
        chdir: /SNCrawler

- name: copy project to all
  hosts: all
  remote_user: vagrant
  sudo: yes
  tags:
   -  build
  tasks:
    - copy: src=/SNCrawler dest=/
