---

- name: apply common configuration to all nodes
  hosts: hdfs_namenodes
  sudo: yes
  tags:
    - prepare
  roles:
    - hdfs_namenode

- name: apply common configuration to all nodes
  hosts: hdfs_datanodes
  sudo: yes
  tags:
    - prepare
  roles:
    - hdfs_datanode