---
# This playbook deploys the entire Mesos cluster infrastructure.
# RUN: ansible-playbook mesos.yml

- name: deploy and configure the mesos masters
  hosts: mesos_masters
  sudo: True
  roles:
    - { role: mesos, mesos_install_mode: "master", tags: ["mesos-master"] }
  environment:
              http_proxy: http://proxy.ifmo.ru:3128
              HTTP_PROXY: http://proxy.ifmo.ru:3128



- name: deploy and configure the mesos slaves
  hosts: mesos_slaves
  sudo: True
  roles:
    - { role: mesos, mesos_install_mode: "slave", tags: ["mesos-slave"] }
  environment:
              http_proxy: http://proxy.ifmo.ru:3128
              HTTP_PROXY: http://proxy.ifmo.ru:3128