---
# This playbook deploys the entire Mesos cluster infrastructure.
# RUN: ansible-playbook mesos.yml

- name: deploy and configure the mesos masters
  hosts: mesos_masters
  sudo: True
  roles:
    - { role: ansible_mesos, mesos_install_mode: "master", tags: ["mesos-master"] }



- name: deploy and configure the mesos slaves
  hosts: mesos_slaves
  sudo: True
  roles:
    - { role: ansible_mesos, mesos_install_mode: "slave", tags: ["mesos-slave"] }