---
- name: apply common configuration to all nodes
  hosts: all
  sudo: yes
  roles:
    - common
  any_errors_fatal: yes

- name: create non-root clusteruser user
  hosts: all
  sudo:	yes
  roles:
    - clusteruser_common
  any_errors_fatal: yes

- name: install mesos on nodes
  hosts: mesos_masters:mesos_slaves
  sudo: True
  roles:
     - { role: mesos, install: true, configure: false, start: false }

- name: configure and run the mesos masters
  hosts: mesos_masters
  sudo: True
  roles:
    - { role: mesos, mesos_install_mode: "master", mesos_cluster_mode: "masters_file", install: false, configure: true, start: true, stop: false}

#- name: configure and run the mesos masters
#  hosts: mesos_slaves
#  sudo: True
#  roles:
#    - { role: mesos, mesos_install_mode: "slave", mesos_cluster_mode: "masters_file", install: false}

#- include: tests/integration-tests.yml
