---
- name: install ganglia monitors
  hosts: ganglia_monitors
  sudo: True
  roles:
    - { role: ganglia , tags: ['ganglia-monitors']}
  environment:
              http_proxy: http://proxy.ifmo.ru:3128
              HTTP_PROXY: http://proxy.ifmo.ru:3128

- name: install ganglia meta
  hosts: ganglia_meta
  sudo: True
  roles:
    - { role: ganglia, is_ganglia_meta: 1,  tags: ['ganglia-meta']}
  environment:
              http_proxy: http://proxy.ifmo.ru:3128
              HTTP_PROXY: http://proxy.ifmo.ru:3128


- name: install ganglia web
  hosts: ganglia_web
  sudo: True
  roles:
    - { role: ganglia, is_ganglia_web: 1, tags: ['ganglia-web']}
  environment:
              http_proxy: http://proxy.ifmo.ru:3128
              HTTP_PROXY: http://proxy.ifmo.ru:3128

- name: install ganglia-api
  hosts: ganglia_web
  sudo: True
  roles:
    - { role: ganglia, is_ganglia_api: 1,  tags: ['ganglia-api']}
  environment:
              http_proxy: http://proxy.ifmo.ru:3128
              HTTP_PROXY: http://proxy.ifmo.ru:3128